app:
    resource: '@SWPEventsBundle/Controller/'
    type: annotation

swp_bridge:
    resource: "@SWPBridgeBundle/Resources/config/routing.yml"

swp_user:
    resource: "@SWPUserBundle/Resources/config/routing.yml"

swp_settings:
    resource: "@SWPSettingsBundle/Resources/config/routing.yml"

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc
