fos_user:
    db_driver: orm
    firewall_name: main
    user_class: SWP\Bundle\UserBundle\Model\User
    from_email:
        address: contact@publisher.dev
        sender_name: Publisher
    registration:
        confirmation:
            enabled: true

nelmio_api_doc: ~

jms_serializer: ~

knp_paginator:
    page_range: 10
    default_options:
        page_name: page
        sort_field_name: sort
        sort_direction_name: direction
        distinct: true

fos_rest:
    zone:
        - { path: ^/api/* }
    versioning:
        enabled: false
    routing_loader:
        default_format: json
    view:
        formats:
            json: true
        view_response_listener: false
    serializer:
        serialize_null: true
    format_listener:
        rules:
            - { path: "^/api", priorities: ['json'], fallback_format: json, prefer_extension: true }
            - { path: "^/", stop: true }
    body_listener:
        decoders:
            json: fos_rest.decoder.jsontoform
    disable_csrf_role: ROLE_API
    exception:
        codes:
            "Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException": 404
            "SWP\\Bundle\\SettingsBundle\\Exception\\InvalidScopeException": 500
        messages:
            "Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException": true
            "SWP\\Bundle\\SettingsBundle\\Exception\\InvalidScopeException": true

swp_storage: ~

swp_bridge:
    persistence:
        orm:
            enabled: true
            classes:
                event:
                    model: SWP\EventsBundle\Model\Event

swp_events:
    persistence:
        orm: true

swp_settings:
    persistence:
        orm: true

swp_user:
    persistence:
        orm: true
